import React from "react";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-gradient-to-b from-black via-indigo-950 to-black text-white font-sans">
            <Header/>
            <main className="container mx-auto px-6 sm:px-8 py-24 pt-40">
                <div
                    className="max-w-4xl mx-auto bg-white/5 border border-white/10 rounded-2xl px-6 sm:px-10 py-10 shadow-xl shadow-black/30 backdrop-blur-sm">
                    <h1 className="text-3xl sm:text-4xl font-bold tracking-tighter mb-4">
                        Terms of Service
                    </h1>
                    <p className="text-sm text-white/60 mb-8">
                        <em>Last updated: 11/24/2025</em>
                    </p>

                    <div className="space-y-8 text-white/90 leading-relaxed">
                        <div>
                            <h2 className="text-2xl font-semibold mb-2">
                                1. Agreement to Terms
                            </h2>
                            <p>
                                By accessing or using SeekHexa (the “Service”), you agree to be
                                bound by these Terms of Service. If you do not agree to these
                                Terms, please do not use the Service. We may update these Terms
                                from time to time, and your continued use of the Service after
                                changes become effective constitutes acceptance of the revised
                                Terms.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">
                                2. Nature of the Service
                            </h2>
                            <p>
                                SeekHexa provides AI-assisted divination, journaling, and
                                reflective tools intended to support personal insight,
                                self-reflection, and spiritual exploration. Any readings,
                                interpretations, or suggestions generated by the Service are
                                for informational and personal use only and should not be
                                considered professional, medical, financial, or legal advice.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">
                                3. Intellectual Property Rights
                            </h2>
                            <p>
                                The Service and its original content, features, and
                                functionality are and will remain the exclusive property of
                                SeekHexa and its licensors. Our trademarks, logos, and trade
                                dress may not be used in connection with any product or service
                                without the prior written consent of SeekHexa.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">4. User Accounts</h2>
                            <p>
                                When you create an account with us, you must provide information
                                that is accurate, complete, and current at all times. Failure to
                                do so constitutes a breach of these Terms and may result in
                                immediate termination of your account. You are responsible for
                                safeguarding the password that you use to access the Service and
                                for any activities or actions under your password.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">
                                5. Prohibited Activities
                            </h2>
                            <p>
                                You may not access or use the Service for any purpose other than
                                that for which we make the Service available. The Service may
                                not be used in connection with any commercial endeavors except
                                those that are specifically endorsed or approved by us. You
                                agree not to misuse the Service, attempt to interfere with its
                                normal operation, or attempt to access it using a method other
                                than the interfaces and instructions we provide.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">6. Disclaimer</h2>
                            <p>
                                SeekHexa is provided as a tool for personal reflection and
                                spiritual exploration. We do not guarantee that any reading or
                                interpretation is accurate, predictive, or applicable to your
                                specific situation. You are solely responsible for any decisions
                                you make based on content generated by the Service.
                            </p>
                            <p className="mt-2">
                                The Service does not provide medical, mental health, financial,
                                or legal advice. You should always seek the guidance of qualified
                                professionals for matters in those areas.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">
                                7. Limitation of Liability
                            </h2>
                            <p>
                                To the maximum extent permitted by applicable law, in no event
                                shall SeekHexa, nor its directors, employees, partners, agents,
                                suppliers, or affiliates, be liable for any indirect, incidental,
                                special, consequential, or punitive damages, including without
                                limitation loss of profits, data, use, goodwill, or other
                                intangible losses, arising out of or in connection with your use
                                of (or inability to use) the Service.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">8. Termination</h2>
                            <p>
                                We may terminate or suspend your account and access to the
                                Service immediately, without prior notice or liability, for any
                                reason whatsoever, including without limitation if you breach
                                these Terms. Upon termination, your right to use the Service
                                will immediately cease. Certain provisions of these Terms shall
                                survive termination, including, without limitation, ownership
                                provisions, warranty disclaimers, indemnity, and limitations of
                                liability.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">9. Governing Law</h2>
                            <p>
                                These Terms shall be governed and construed in accordance with
                                the laws of the jurisdiction in which the company is
                                established, without regard to its conflict of law provisions.
                                You agree to submit to the personal jurisdiction of such courts
                                for the purpose of litigating all such claims or disputes.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">
                                10. Changes to These Terms
                            </h2>
                            <p>
                                We reserve the right, at our sole discretion, to modify or
                                replace these Terms at any time. If a revision is material, we
                                will provide at least 30 days&apos; notice prior to any new
                                terms taking effect, for example by updating the “Last updated”
                                date or providing in-app notification. What constitutes a
                                material change will be determined at our sole discretion.
                            </p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-semibold mb-2">11. Contact Us</h2>
                            <p>
                                If you have any questions about these Terms, please contact us
                                at <span className="underline">help@seekhexa.com</span>.
                            </p>
                        </div>
                    </div>
                </div>
            </main>
            <Footer/>
        </div>
    );
}